### ISSUE TITLE
[Documentation] Add contributor's guide

### ISSUE THREAD

**Issue by Oddball777** [GraphingLib/GraphingLib#497] opened 2024-06-11 00:36 UTC
### Select the subject of this issue:

- [x] GL documentation (readthedocs)
- [ ] Docstrings and/or comments within the code

### Describe the changes which need to be made
Add contributor's guide to both readthedocs site and in repo as contributions.md

**Comment by yalap13** [comment] 2024-06-12 15:39
Duplicate of #227

**Closed by yalap13** 2024-06-12 15:39 UTC
Labels: documentation
